First-Plug/First-Plug-Platform-Api

src/products/products.service.ts
Fixed products grouping. Ignored color properties
=> Fix (products): fixed products agrupation

src/products/products.service.ts, src/products/schemas/product.schema.ts, src/products/validations/create-product.zod.ts
Possible solution for unique  serial number, add sparse: true => serial number should be null, do not send an empty string, it wont work
=> Serial Number Unique

src/products/products.service.ts
bulkcreate function adapated to accept empty strings for serial number prop
=> BulkCreate

src/members/members.service.ts
handle duplicate email when updating
=> Fix(member service): add try catch in update function

src/members/members.service.ts
=> Fix(member): Add validation to match assignedEmail with members

src/members/members.service.ts
=> fix(bulkcreate): delete products from product collection after

src/products/products.service.ts
build other smaller methods to handle different scenarios for updating stock
=> refactor(stock) update Method

src/products/products.service.ts
=> handle assignedEmail as "" and add acquisitionDate

src/members/members.service.ts
filter out undefined properties and prevent product updates in member update
=> feat(updateMember)

src/members/members.service.ts, src/products/products.service.ts
Ensure assignedEmail is preserved when assigning product to member
=> Fix(updateMember / createProduct)

src/products/products.service.ts
=> fix(stock): set isDeleted = true when deleting product

src/members/members.service.ts
using Spanish collation to handle names with tildes  correctly. Updated MembersService findAll method to use collation for proper sorting.
=> Sorted members alphabetically in the backend 

src/auth/auth.service.ts, src/tenants/tenants.service.ts
to propagate recoverable config and billing info
=> when user login, verify tenants and createdAt, 

src/config/env.config.ts, src/config/environments.validation.ts, src/tenants/tenants.service.ts
=> Add a new webHook to sent messages to slack

src/products/products.service.ts
setting in the recoverable prop, do not change to
global config
=> fix: when uddating product keep the isRecoverable

src/tenants/tenants.service.ts
=> Add comouter condition and additionalInfo to product schema

src/common/events/product-updated.event.ts, src/common/events/types.ts, src/products/products.service.ts, src/products/validations/create-product.zod.ts, src/shipments/listeners/product-updated.listener.ts, src/shipments/shipments.module.ts, src/shipments/shipments.service.ts
consolidate new product to existing shipment
=> WIP: create snapshot when create shipment + when

src/shipments/shipments.service.ts
=> fix order, first determine product status,

src/shipments/shipments.service.ts
=> FIX: separate logic for order id creation and

src/logistics/logistics.sevice.ts, src/products/products.service.ts, src/shipments/shipments.service.ts
=> FIX: better update of asset snapshot, when active

src/members/helpers/normalizeKeys.ts, src/members/members.service.ts, src/products/helpers/history.helper.ts, src/products/products.service.ts, src/products/schemas/product.schema.ts, src/shipments/shipments.service.ts
=> Create lastserialNumber prop to save serialNumber

src/logistics/logistics.sevice.ts
(cancel sh)
when member still have other active shipments
=> FIX: do not change flag active shipment to false

src/logistics/logistics.sevice.ts
=> FIX: something wrong when changing product status

src/users/dto/update-user-superadmin.dto.ts, src/users/schemas/user.schema.ts, src/users/users.service.ts
=> FIX: when update user role to superadmin, erase

src/superadmin/superadmin.module.ts, src/superadmin/superadmin.service.ts
=> when shipment status = received - update member and
